### ISSUE TITLE
Use a single repository to trial two different environments

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/web-test#10]
To have different content in the `deploy-s3.yml` and `deploy-s3-bucket-policy.json` depending of the branch: `dev` and `master`

## Summary

Use a single repository to trial two different environments:
* `staging` with the content in the `dev` branch, and
* `production` with the content in the `master` branch

## Expected Behavior
The repository is connected to two different websites.

When a PR is created, the CI should validate the generated HTML files under
`_site`, and exit with non-zero status so that PR author will be notified
before merging.

## Requirements and rationales

Test

## Context

* In order to maintain different configuration in the .yml and .json file, I believe that we need to add these two files to the .gitignore file.

If I add the following two statements to the `.gitignore` file, will this allow me two have two different content for these files in `dev` and `master` branch, and therefore point to different websites?

```
 .github/workflows/deploy-s3.yml
 .github/workflows/deploy-s3-bucket-policy.json
```
Should this content be added in a specific order inside of the `.gitigonre` file?

**Comment by trombik** [comment]
a great issue!
