### ISSUE TITLE
update dev environment upon merging into dev

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/web-test#21]
For me it is more useful to update the dev environment only when the PR is merged into dev, not when it is submitted. Otherwise, I will only be able to validate the latest PR. In a repository there will be several people contributing, I need to evaluate how the website looks like after merge each PR

Is possible to build the dev environment only when the PR is merged?

**Comment by trombik** [comment]
would please you clarify what exactly you want to do? the template is there for a reason. the more you clearly state the issue, the more likely you will get what you really want (and the less time and money will be wasted as a result).

- which work flow do you want to run on push and pull request?
- which work flow do you want not to run on push and pull request?
- when a user create a PR, what should happen?
- when a user merge a PR, what should happen?
- lastly, why do you need the change?

**Comment by jpradocueva** [comment]
Tomi, your form may work for you but does work for me. I don't fully understand all the terminology that you use.

This is what I need.

In the **Development** branch
* When a Pull Request is **merged** into this branch, this website  (development) http://mywebtest.s3-website-us-west-1.amazonaws.com/ should be updated

At the moment, it seems that each time a Pull Request is submitted the development website is updated. In this way you can see how it looks like the latest PR. This is not my use case.

This is my use case, only rebuilt the development website after a PR has been merged. When PRs are submitted, nothing happen. I am testing, trying to understand how things work. At this moment, I don't need any thing else.
