### ISSUE TITLE
If further features are needed I will let you know.

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/web-test#22]
A few features have been added which I don't fully understand. This repo is for me to understand things. So, before add any new feature I would like to understand the function of every file that has been added. I will ask you question when I have the time to review its content.
For the moment, lets to don't add any more feature. I am cannot follow up all the changes.

**Comment by trombik** [comment]
as I understood it, this is not about an issue. I will not change anything unless asked through issues. if that is not your intention, please reopen
