### ISSUE TITLE
New policy - the first resource correct?

### ISSUE THREAD

**Issue by jpradocueva** [standardshub/web-test#7]
I have created a new policy for "deploy-web-prod-policy"

But I am not sure if the first resource has been written correctly. I did some changes to the original and now I am not sure.

Resource 1:  "Resource": "arn:aws:s3:::mywebtestprod"
Resource 2:  "Resource": "arn:aws:s3:::mywebtestprod/*"

``` JSON
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::mywebtestprod"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::mywebtestprod/*"
        }
    ]
}
```

**Comment by trombik** [comment]
please read thorough the documentation first. you need to understand AWS basic before trying to do something more advanced. when you install the CLI, and you confirm the installation works, let me know. https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html

**Comment by jpradocueva** [comment]
The above excerpt was created directly via AWS web console. I pasted it here to help you to identify if my description of the first resource is correct:

"Resource": "arn:aws:s3:::mywebtestprod"

versus

 "Resource": "arn:aws:s3:::mywebtestprod/*"

**Comment by trombik** [comment]
what is the issue? what is your intention? what doesn't work as intended?

**Comment by jpradocueva** [comment]
Ok, let me get all my requirements together first.
Please don't act in any of the PRs and issues until I have done my work then we can discuss about what I try to do.

**Comment by trombik** [comment]
when I am given a precise and accurate requirements, I can implement requests quickly and efficiently, for example see #2. please see the PR templates I have just submitted. thanks for your understanding.

**Comment by jpradocueva** [comment]
The correct value was: Resource 1: "Resource": "arn:aws:s3:::mywebtestprod"
